name: 'Kerio VPN Action'
description: 'Make a VPN connection'
author: 'Trilogy'
branding:
  icon: 'archive'
  color: 'gray-dark'
inputs:
  vpn-version:
    description: 'Kerio vpn client version to download.'
    required: true
    default: 9.3.5-4367
  vpn-username:
    description: 'Service user.'
    required: true
  vpn-password:
    description: 'Service user password.'
    required: true
  vpn-auth-code:
    description: 'To make the 2SV, kerio vpn needs to browse a page with TOTP_CONTROL as a cookie.'
    required: true
  max-verify-attempt:
    description: 'Curl attempt count to verify the connection.'
    required: true
    default: 5
  max-setup-attempt:
    description: 'Setup attempt count.'
    required: true
    default: 5
  kvn-timeout:
    description: 'Kerio vpn client kvnet start timeout.'
    required: true
    default: 30
runs:
  using: 'composite'
  steps:
    - run: |
        die() {
          echo "::Error! ::$1 empty"
          exit 1
        }
        [[ "${{ inputs.vpn-version }}" = "" ]] && {
          die "vpn-version"
        }
        [[ "${{ inputs.vpn-username }}" = "" ]] && {
          die "vpn-username"
        }
        [[ "${{ inputs.vpn-password }}" = "" ]] && {
          die "vpn-password"
        }
        [[ "${{ inputs.vpn-auth-code }}" = "" ]] && {
          die "vpn-auth-code"
        }
        [[ "${{ inputs.max-verify-attempt }}" = "" ]] && {
          die "max-verify-attempt"
        }
        [[ "${{ inputs.max-setup-attempt }}" = "" ]] && {
          die "max-setup-attempt"
        }
        [[ "${{ inputs.kvn-timeout }}" = "" ]] && {
          die "kvn-timeout"
        }
        ${{ github.action_path }}/vpn.sh \
          "${{ inputs.vpn-version }}" \
          "${{ inputs.vpn-username }}" \
          "${{ inputs.vpn-password }}" \
          "${{ inputs.vpn-auth-code }}" \
          "${{ inputs.max-verify-attempt }}" \
          "${{ inputs.max-setup-attempt }}" \
          "${{ inputs.kvn-timeout }}"
      shell: bash
